### ISSUE TITLE
Issue while running mvn clean install

### ISSUE THREAD

**Issue by jmbabazi** [Bhamni/bahmni-reports#1]
* I've been getting the below error, it looks like there is a missing path in pom.xml . Any help is high appreciated. (note: I've also got a similar error while running the same command on Bhamni/bahmni-core)

* I've tried to delete the /root/.m2 directory but I still get the error.

* Is there a repository with already built bahmni omods?

Project ID: org.bahmni.module:mail-appender
https://github.com/Bhamni/bahmni-reports/issues/new#
Reason: Error getting POM for 'org.bahmni.module:mail-appender' from the repository: Unable to read local copy of metadata: Cannot read metadata from '/root/.m2/repository/org/bahmni/module/mail-appender/5.3-SNAPSHOT/maven-metadata-bahmni-artifactory.xml': end tag name </body> must match start tag name <hr> from line 7 (position: TEXT seen ...</address>\n</body>... @9:8) 
  org.bahmni.module:mail-appender:pom:5.3-SNAPSHOT
![mvn-bahmni](https://cloud.githubusercontent.com/assets/12864648/10845411/fade9912-7edd-11e5-902f-48dd8c2ad27e.png)

for project org.bahmni.module:mail-appender

**Comment by aj-jaswanth** [comment]
You  are using an older version of maven. Please install a new version, at least 3.3.

**Comment by aj-jaswanth** [comment]
The reason is that older maven doesn't know how to redirect for HTTP 302 responses.

**Comment by jmbabazi** [comment]
Thank you, will install new version of maven.
